import { Component, Input } from "@angular/core";
import {
  LucideDynamicIcon,
  LucideIconData,
  LucideAperture,
  LucideLayoutDashboard,
  LucideClipboardList,
  LucideFiles,
  LucideClipboardCheck,
  LucideBell,
  LucideUserRound,
  LucideLogOut,
  LucideArrowRight,
  LucideArrowLeft,
  LucidePlus,
  LucideSearch,
  LucideChevronDown,
  LucideCheck,
  LucideX,
  LucideExternalLink,
  LucideMenu,
  LucideClock3,
  LucideFlag,
  LucideSparkles,
  LucideLockKeyhole,
  LucideRefreshCw,
  LucideInfo,
  LucideCodeXml,
  LucideSlidersHorizontal,
  LucideArrowDownUp,
  LucideTriangleAlert,
  LucideCircleX,
  LucideEye,
  LucideEyeOff,
  LucideUpload,
  LucidePencil,
  LucideTrash2,
  LucideChartNoAxesCombined,
  LucideUsers,
  LucideCircleCheck,
  LucideSettings,
} from "@lucide/angular";
@Component({
  selector: "pl-icon",
  standalone: true,
  imports: [LucideDynamicIcon],
  template: `<svg
    [lucideIcon]="icons[name] || icons['lens']"
    [size]="size"
    [strokeWidth]="1.8"
    aria-hidden="true"
  ></svg>`,
})
export class IconComponent {
  @Input() name = "lens";
  @Input() size = 20;
  readonly icons: Record<string, LucideIconData> = {
    lens: LucideAperture.icon,
    dashboard: LucideLayoutDashboard.icon,
    criteria: LucideClipboardList.icon,
    submissions: LucideFiles.icon,
    reviews: LucideClipboardCheck.icon,
    bell: LucideBell.icon,
    user: LucideUserRound.icon,
    logout: LucideLogOut.icon,
    arrow: LucideArrowRight.icon,
    back: LucideArrowLeft.icon,
    plus: LucidePlus.icon,
    search: LucideSearch.icon,
    chevron: LucideChevronDown.icon,
    check: LucideCheck.icon,
    close: LucideX.icon,
    external: LucideExternalLink.icon,
    menu: LucideMenu.icon,
    clock: LucideClock3.icon,
    flag: LucideFlag.icon,
    spark: LucideSparkles.icon,
    lock: LucideLockKeyhole.icon,
    refresh: LucideRefreshCw.icon,
    info: LucideInfo.icon,
    code: LucideCodeXml.icon,
    filter: LucideSlidersHorizontal.icon,
    sort: LucideArrowDownUp.icon,
    warning: LucideTriangleAlert.icon,
    error: LucideCircleX.icon,
    eye: LucideEye.icon,
    "eye-off": LucideEyeOff.icon,
    upload: LucideUpload.icon,
    edit: LucidePencil.icon,
    delete: LucideTrash2.icon,
    chart: LucideChartNoAxesCombined.icon,
    users: LucideUsers.icon,
    success: LucideCircleCheck.icon,
    settings: LucideSettings.icon,
  };
}
